version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${UID}:${GID}
    group_add:
      - '${RENDER_GID}'
    volumes:
      - ${DATA_CONFIG}:/config
      - ${DATA_CACHE}:/cache
      - ${DATA_MEDIA}:/media
    restart: 'unless-stopped'
    environment:
      - VIRTUAL_HOST=${JELLY_HOST}
      - VIRTUAL_NETWORK=${PROXY_HOST}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=${JELLY_HOST}
      - LETSENCRYPT_EMAIL=${LE_EMAIL}
      - JELLYFIN_PublishedServerUrl=https://${JELLY_HOST}
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096
      - 7359:7359/udp
    networks:
      - proxy-net
networks:
  proxy-net:
    name: home-server_proxy-tier
    external: true
